CFG_SOCKETS = "Sockets"
CFG_SOCKET_IP = "Ip"
CFG_ACTION_SOCKET = "ActionPort"
CFG_REPLY_SOCKET = "ReplyPort"
CFG_SENSOR_SOCKET = "SensorPort"

CFG_REST_API = "RestAPI"
CFG_REST_API_BASE_IP = "BaseUrl"
