Sockets:
  Action: 'ws://localhost:3001'
  Reply: 'ws://localhost:3002'
  Sensor: 'ws://localhost:3003'
  
RestAPI:
  BaseUrl: "http://localhost:3000/"
  Port: 3000

Serial:
  Port: "COM5"
  baud_rate: 9600
  timeout: 0.5